name: Release Better Alert Icons

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Zip files
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#v}"
          FILENAME=better-alert-icons_${VERSION}
          git archive --format=zip --prefix=${FILENAME} HEAD > ${FILENAME}.zip

      - name: Release files
        run: gh release create ${{ github.ref_name }} better-alert-icons_${{ github.ref_name }}.zip --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
