name: Release Better Alert Icons

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip files
        run: git archive --format=zip HEAD > better-alert-icons_${{ github.refname }}.zip

      - name: Release files
        run: gh release create ${{ github.ref_name }} better-alert-icons_${{ github.refname }}.zip --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
